[pytest]
addopts =
    -vv --capture=tee-sys
    --html=./artifacts/report/report.html
    --self-contained-html
    -p no:warnings

testpaths = test

markers =
    webtest: mark a test as a webtest.
    create_account: mark a test as create and signup account.
    delete_account: mark a test as delete existing_account.
    existing_account: mark a test as existing_login check.
    valid_login: mark a test as valid_login check.
    invalid_login: mark a test as invalid_login check.
    get_first_product: mark a test as get first_product all details.
    get_searched_product: mark a test as get searched_product count.
    add_product: mark a test as get add_product.
    payment: mark a test as pay to customer.
    contact: mark a test as to contact product owner.
    end_to_end: mark a test as end_to_end process of account creation, add product, checkout and payment
